In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"D:\Student Risk Analysis\Student Placement Dataset\train.csv")

In [3]:
df.head()

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,1048,22,Female,B.Tech,ECE,6.29,0,3,4,6,51,5,1,3,Not Placed
1,37820,20,Female,BCA,ECE,6.05,1,4,6,8,59,8,2,1,Not Placed
2,49668,22,Male,MCA,ME,7.22,1,4,6,6,58,6,2,2,Not Placed
3,19467,22,Male,MCA,ME,7.78,2,4,6,6,90,4,2,0,Placed
4,23094,20,Female,B.Tech,ME,7.63,1,4,6,5,79,6,2,0,Placed

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            45000 non-null  int64
 1   Age                   45000 non-null  int64
 2   Gender                45000 non-null  str
 3   Degree                45000 non-null  str
 4   Branch                45000 non-null  str
 5   CGPA                  45000 non-null  float64
 6   Internships           45000 non-null  int64
 7   Projects              45000 non-null  int64
 8   Coding_Skills         45000 non-null  int64
 9   Communication_Skills  45000 non-null  int64
 10  Aptitude_Test_Score   45000 non-null  int64
 11  Soft_Skills_Rating    45000 non-null  int64
 12  Certifications        45000 non-null  int64
 13  Backlogs              45000 non-null  int64
 14  Placement_Status      45000 non-null  str
dtypes: float64(1), int64(10), str(4)
memory usage: 5.1 MB

In [5]:
df.describe()

,Student_ID,Age,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs
count,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,24977.962600,20.999333,7.002290,0.774089,3.734222,5.691800,5.501644,69.385356,5.501644,1.800956,0.888133
std,14425.605704,1.995071,0.993855,0.844750,0.923738,1.994674,1.515374,13.909710,1.238722,0.650104,0.970954
min,1.000000,18.000000,4.500000,0.000000,1.000000,1.000000,1.000000,35.000000,1.000000,0.000000,0.000000
25%,12509.750000,19.000000,6.320000,0.000000,3.000000,4.000000,4.000000,60.000000,5.000000,1.000000,0.000000
50%,24957.500000,21.000000,7.000000,1.000000,4.000000,6.000000,6.000000,69.000000,5.000000,2.000000,1.000000
75%,37475.250000,23.000000,7.670000,1.000000,4.000000,7.000000,7.000000,79.000000,6.000000,2.000000,2.000000
max,50000.000000,24.000000,9.800000,3.000000,6.000000,10.000000,10.000000,100.000000,10.000000,3.000000,3.000000

In [6]:
df.isnull().sum()

Student_ID              0
Age                     0
Gender                  0
Degree                  0
Branch                  0
CGPA                    0
Internships             0
Projects                0
Coding_Skills           0
Communication_Skills    0
Aptitude_Test_Score     0
Soft_Skills_Rating      0
Certifications          0
Backlogs                0
Placement_Status        0
dtype: int64

In [8]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Degree', 'Branch', 'CGPA',
       'Internships', 'Projects', 'Coding_Skills', 'Communication_Skills',
       'Aptitude_Test_Score', 'Soft_Skills_Rating', 'Certifications',
       'Backlogs', 'Placement_Status'],
      dtype='str')

In [9]:
df.shape

(45000, 15)

In [10]:
df.dtypes

Student_ID                int64
Age                       int64
Gender                      str
Degree                      str
Branch                      str
CGPA                    float64
Internships               int64
Projects                  int64
Coding_Skills             int64
Communication_Skills      int64
Aptitude_Test_Score       int64
Soft_Skills_Rating        int64
Certifications            int64
Backlogs                  int64
Placement_Status            str
dtype: object

In [11]:
df.value_counts("Placement_Status")

Placement_Status
Not Placed    28688
Placed        16312
Name: count, dtype: int64

In [13]:
df.value_counts("Gender")

Gender
Female    22620
Male      22380
Name: count, dtype: int64

In [14]:
df.value_counts("Degree")

Degree
B.Sc      11357
B.Tech    11305
MCA       11289
BCA       11049
Name: count, dtype: int64